### https://taskfile.dev
###---------------------

version: '2'

vars:
  BUILTAT:
    sh: date +%s
  VERSION: 0.0.0
  LDFLAGS: -X 'main.version={{.VERSION}}' -X 'main.builtAt={{.BUILTAT}}'

tasks:
  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test -cover -v ./...

  hamm:
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o _examples/bin/hamm _examples/hamm/hamm.go

  slink:
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o _examples/bin/slink _examples/slink/slink.go

  examples:
    cmds:
      - task: hamm
      - task: slink

  default:
    cmds:
      - task: lint
      - task: test
      - task: examples
